# Generated by Django 2.0.13 on 2019-11-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_imageset_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageset',
            name='folder',
            field=models.TextField(default='/'),
        ),
    ]
