# Generated by Django 2.0.13 on 2019-11-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_imageset_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='folder',
            field=models.CharField(default='/', max_length=200),
        ),
    ]
