# Generated by Django 2.0.13 on 2019-12-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0020_auto_20191115_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='assignee',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
